### ISSUE TITLE
Target Opencore version

### ISSUE THREAD

**Issue by eriskhan** [kodowiec/HP-Elitebook-x360-1040-G6-Opencore#1]
Hey there! Could you please specify which Opencore version does this config target?

**Comment by kodowiec** [comment]
I'm still running OC 0.6.7 so I believe that's the target version of this config

**Comment by eriskhan** [comment]
Thanks a lot!

**Comment by eriskhan** [comment]
Hey there @kodowiec! Could you please share your USB Mapping? I've got some issues with Bluetooth, seems to be due to incorrect mapping...

**Comment by kodowiec** [comment]
@eriskhan there you go 
[USBMap.kext.zip](https://github.com/kodowiec/HP-Elitebook-x360-1040-G6-Opencore/files/7750648/USBMap.kext.zip)
